services:
  ocr-api:
    build: ./ocr_service
    container_name: paddleocr
    ports:
      - "8010:8010"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
                                                                                                                  
